apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: module-3
spec:
  interval: 10m
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      version: 16.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 10m
  values:
    image:
      registry: docker.io
      repository: bitnami/mongodb
      tag: 8.0.9-debian-12-r0
    pullPolicy: IfNotPresent
    replicaCount: 3
    updateStrategy:
      type: RollingUpdate
    useStatefulSet: true
    architecture: "replicaset"
    persistence:
      enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        cpu: 2
        memory: 256Mi
    arbiter:
      enabled: true
      resources:
        requests:
          memory: 50Mi
          cpu: 20m
        limits:
          cpu: 1
          memory: 256Mi
  valuesFrom:
    - kind: Secret
      name: mongodb-secrets-module-3
