apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: module-3
spec:
  interval: 5m
  releaseName: rabbitmq
  chartRef:
    name: rabbitmq-charts
    namespace: flux-system
    kind: OCIRepository
  values:
    image:
      registry: docker.io
      repository: bitnami/rabbitmq
      tag: 4.1.0-debian-12-r0
    pullPolicy: IfNotPresent
    replicaCount: 3
    updateStrategy:
      type: RollingUpdate
    persistence:
      enabled: true
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        cpu: 2
        memory: 256Mi
    clustering:
      forceBoot: true
    service:
      type: LoadBalancer
    extraConfiguration: "## increase to 7 days
      consumer_timeout = 604800000  "
  valuesFrom:
    - kind: Secret
      name: rabbitmq-secrets-module-3
