apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets-module-3
  namespace: module-3
type: Opaque
stringData:
  auth:
    username: admin
    password: "123456"
    erlangCookie: 6ddcae89dc635c0ba5f28f2f667ece37
